Alter tf-deploy branch check to group environment classes
`app prod`, `all/prod`, `core/prod`. `all/sms-prod`, and `sms/prod`
should ALL require deployment from `stages/prod`.   This modifies
`td-deploy` to group environment classes (environments ending in the
same postfix.)   `sms-prod`, `secops-prod`, and `prod` all get
combined into the `prod` environment class.

* `tf-deploy all/sms-prod apply` from `stages/prod`: No errors
* `tf-deploy all/sms-prod apply` from `stages/sms-prod`:
~~~
warning: Current git branch is not the expected stages/prod

Environment: sms-prod
Expected branch: stages/prod
Actual branch:   stages/sms-prod

Error: Strict environment. Branch name must be stages/prod
(set DEPLOY_WEIRD_BRANCH=1 to skip this check in current environment)
~~~
* `DEPLOY_WEIRD_BRANCH=1 tf-deploy all/sms-prod plan` from `stages/sms-prod`:
~~~
warning: Current git branch is not the expected stages/prod

Environment: sms-prod
Expected branch: stages/prod
Actual branch:   stages/sms-prod
~~~